version: '3.8'

services:
  hello-world:
    image: nginx:alpine
    container_name: hello-world-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.docker.compose.project=hello-world"
      - "description=Hello World Web Application"
    networks:
      - hello-world-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 SSL 证书管理
  # certbot:
  #   image: certbot/certbot
  #   container_name: hello-world-certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d your-domain.com --agree-tos
  #   depends_on:
  #     - hello-world

networks:
  hello-world-network:
    driver: bridge
    name: hello-world-net

# 可选：数据卷（如果需要持久化数据）
# volumes:
#   hello-world-data:
#     driver: local